# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql